worker_processes auto;

error_log /tmp/error.log warn;
pid /tmp/nginx.pid;

events {
    worker_connections 1024;
}

http {
    client_body_temp_path /tmp/client_temp;
    proxy_temp_path       /tmp/proxy_temp;
    fastcgi_temp_path     /tmp/fastcgi_temp;
    uwsgi_temp_path       /tmp/uwsgi_temp;
    scgi_temp_path        /tmp/scgi_temp;
    client_max_body_size 500m;

    server {
        listen 8081;

        root /symbols;
        autoindex on;

        location / {
            autoindex on;

            # In the future we may want to support WebDav methods
            # dav_methods PUT DELETE MKCOL COPY MOVE;
            create_full_put_path on;
            dav_access user:rw group:rw all:r;
        }
    }
}